name: Unit Test

on:
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/test.yml'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Run tests
      working-directory: src
      run: dotnet test